export const SIBEBAR = "SIBEBAR";
export const LOADER = "LOADER";
export const RECIPE_BOOK_LIST = "RECIPE_BOOK_LIST";
export const SET_RECIPE_BOOK_LIST = "SET_RECIPE_BOOK_LIST";
export const SEARCH_IMAGE = "SEARCH_IMAGE";
export const GET_SEARCH_IMAGE = "GET_SEARCH_IMAGE";
